### ISSUE TITLE
1.18 Trick Failed

### ISSUE THREAD

**Issue by CosmicRedWolfRx** [SpacePython12/AP-Launcher#5]
(insert description of bug here)
***
Log contents:
```
Traceback (most recent call last):
  File "launcher_process.py", line 326, in <module>
  File "launcher_process.py", line 326, in <listcomp>
KeyError: 'clientid'

```

**Comment by SpacePython12** [comment]
A fix will be out for this problem in 1.0.

For now, use this trick:
Go to your Minecraft directory and navigate to `/versions/1.18/1.18.json` and open it. Use CTRL-F to find `"--clientId", "${clientid}", "--xuid", "${auth_xuid}", ` and delete it. Save the file. Then rerun Minecraft and the problem should be fixed!
