### ISSUE TITLE
Launcher wont open

### ISSUE THREAD

**Issue by CosmicRedWolfRx** [SpacePython12/AP-Launcher#6]
When I open the launcher it immediately goes to an error messages
***
Log contents:
```
Traceback (most recent call last):
  File "APLauncher.pyw", line 630, in <module>
  File "APLauncher.pyw", line 143, in __init__
  File "PIL\ImageTk.py", line 89, in __init__
  File "PIL\ImageTk.py", line 58, in _get_image_from_kw
  File "PIL\Image.py", line 2968, in open
PIL.UnidentifiedImageError: cannot identify image file 'assets/background.png'

```

**Comment by CosmicRedWolfRx** [comment]
nvm it fixed itself
