### ISSUE TITLE
Specific Versions won't launch

### ISSUE THREAD

**Issue by CosmicRedWolfRx** [SpacePython12/AP-Launcher#7]
Not a huge problem but 1.8.9 or 1.12.2 won't launch
***
1.8.9 Log
***
Log contents:
```
Traceback (most recent call last):
  File "launcher_process.py", line 286, in <module>
KeyError: 'arguments'

```
***
1.12 Issue Log
***
Log contents:
```
Traceback (most recent call last):
  File "launcher_process.py", line 286, in <module>
KeyError: 'arguments'

```

**Comment by SpacePython12** [comment]
Has been fixed in 1.0. 

Unfortunately, for now there isn’t a fix for the current version of AP Launcher without extensive coding knowledge.
