### ISSUE TITLE
Launcher isnt working stupid

### ISSUE THREAD

**Issue by JustAnotherCasual** [SpacePython12/AP-Launcher#8]
[2022-02-02 14:36:45,776] [Launcher Interface/INFO]: Reading base files...
[2022-02-02 14:36:45,781] [Launcher Interface/INFO]: 	Read launcher_accounts.json.
[2022-02-02 14:36:45,789] [Launcher Interface/INFO]: 	Read 1.18.json.
[2022-02-02 14:36:45,817] [Launcher Interface/INFO]: 	Read 1.18.json.
[2022-02-02 14:36:45,817] [Launcher Interface/INFO]: Downloading files...
[2022-02-02 14:36:45,829] [Launcher Interface/WARNING]: Unable to download asset index.
[2022-02-02 14:36:45,830] [Launcher Interface/INFO]: Updating assets...
[2022-02-02 14:36:46,181] [Launcher Interface/ERROR]: 'str' object has no attribute 'sleep'
Traceback (most recent call last):
  File "launcher_process.py", line 276, in <module>
  File "launcher_process.py", line 144, in update_files
  File "launcher_process.py", line 133, in download_assets
AttributeError: 'str' object has no attribute 'sleep'

fix plz

**Comment by SpacePython12** [comment]
That’s strange, I wonder why is it doing that?

**Comment by SpacePython12** [comment]
Fixed in v1.0.2
